@startuml
title SmartHome Context Diagram

top to bottom direction

!include ../libs/C4_Context.puml

Person(user, "User", "A user of the smart home system")
Person(employee, "Installation employee", "Employee installing devices")
System(SmartHomeDevices, "Smart Home Devices", "System managing devices, heating control and temperature monitoring")
System(SmartHomeSystem, "Smart Home System", "Smart Home Devices")

Rel(user, SmartHomeSystem, "Uses the system")
Rel(employee,SmartHomeDevices,"Installing devices")
Rel(SmartHomeSystem,SmartHomeDevices,"Controls devices, fetching monitoring data")
Rel(SmartHomeDevices,SmartHomeSystem,"Registering in system in start")

@enduml